<?php

return [
    'template_path' => resource_path('documents/BatStateU-FO-RES-02-Detailed-Research-Proposal.docx'),
    'proponent_agency' => '',
    'default_campus' => 'BatStateU The NEU ARASOF-Nasugbu Campus',
    'maximum_narrative_length' => 100000,
    'section_headings' => [
        'project-information' => 'I. Research Project Title:',
        'research-agenda' => 'II. BatStateU Research Agenda:',
        'sdgs' => 'III. Sustainable Development Goal:',
        'project-team' => 'IV. Project Leader:',
        'proponent' => 'V. Proponent Agency:',
        'cooperating-agency' => 'VI. Cooperating Agency:',
        'executive-brief' => 'VII. Executive Brief:',
        'rationale' => 'VIII. Rationale:',
        'objectives' => 'IX. Objectives of the Project:',
        'expected-outputs' => 'X. Expected Output of the Project:',
        'literature' => 'XI. Review of Related Literature:',
        'methodology' => 'XII. Methodology:',
        'responsibilities' => 'XIII. Duties and Responsibilities of each member:',
        'work-plan' => 'XIV. Major Activities/Workplan (Gantt Chart):',
        'budget' => 'XV. Line-Item Budget:',
        'references' => 'XVI. References:',
        'curriculum-vitae' => 'XVII. Curriculum Vitae:',
    ],
    'image_sections' => [
        'executive_brief' => 'Executive Brief',
        'rationale' => 'Rationale',
        'introduction' => 'Review of Related Literature — opening paragraphs',
        'related_literature' => 'Review of Related Literature',
        'research_design' => 'Research Design',
        'specific_methods' => 'Specific Methods',
        'data_analysis' => 'Data Analysis',
    ],
    'professional_titles' => [
        'Asst Prof.',
        'Assoc Prof.',
        'Prof.',
        'Dr.',
        'Engr.',
        'Atty.',
    ],
    'sdgs' => [
        1 => 'No Poverty',
        2 => 'Zero Hunger',
        3 => 'Good Health & Well-being',
        4 => 'Quality Education',
        5 => 'Gender Equality',
        6 => 'Clean Water & Sanitation',
        7 => 'Affordable and Clean Energy',
        8 => 'Decent Work & Economic Growth',
        9 => 'Industry, Innovation, & Infrastructure',
        10 => 'Reduced Inequalities',
        11 => 'Sustainable Cities & Communities',
        12 => 'Responsible Consumption & Production',
        13 => 'Climate Action',
        14 => 'Life Below Water',
        15 => 'Life on Land',
        16 => 'Peace, Justice, & Strong Institutions',
        17 => 'Partnerships for the Goals',
    ],
    'expected_outputs' => [
        'publication' => 'Publication',
        'patent' => 'Patent',
        'product' => 'Product',
        'people_service' => 'People Service',
        'place_partnership' => 'Place & Partnership',
        'policy' => 'Policy',
        'social_impact' => 'Social Impact',
        'economic_impact' => 'Economic Impact',
    ],
    'methodology' => [
        'research_design' => 'Research Design',
        'specific_methods' => 'Specific Method to obtain the objectives',
        'data_analysis' => 'Data Analysis',
    ],
];
