<?php

use App\Models\ProposalVersionFile;

return [
    'detailed-proposal' => [
        'document_type' => ProposalVersionFile::TYPE_DETAILED_PROPOSAL,
        'label' => 'Detailed Research Proposal',
        'description' => 'The complete narrative proposal for the research project.',
        'order' => 1,
        'mode' => 'upload',
        'template_slug' => 'detailed-research-proposal',
        'sample_slug' => 'detailed-proposal',
        'accepted_extensions' => ['pdf', 'doc', 'docx'],
        'accepted_mime_types' => [
            'application/pdf',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => 25600,
    ],
    'work-plan' => [
        'document_type' => ProposalVersionFile::TYPE_WORK_PLAN,
        'label' => 'Attachment A: Work Plan',
        'description' => 'Objectives, expected outputs, activities, and the Year 1 M1–M12 schedule.',
        'order' => 2,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'work-plan',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'line-item-budget' => [
        'document_type' => ProposalVersionFile::TYPE_LINE_ITEM_BUDGET,
        'label' => 'Attachment B: Line-Item Budget',
        'description' => 'Project staff, approved budget line items, automatic totals, and research-office certification.',
        'order' => 3,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'line-item-budget',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'expense-breakdown' => [
        'document_type' => ProposalVersionFile::TYPE_EXPENSE_BREAKDOWN,
        'label' => 'Estimated Expense Breakdown',
        'description' => 'The detailed spreadsheet supporting the proposed expenses.',
        'order' => 4,
        'mode' => 'upload',
        'template_slug' => 'estimated-expense-breakdown',
        'sample_slug' => 'expense-breakdown',
        'accepted_extensions' => ['xls', 'xlsx'],
        'accepted_mime_types' => [
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => 25600,
    ],
    'curriculum-vitae' => [
        'document_type' => ProposalVersionFile::TYPE_CURRICULUM_VITAE,
        'label' => 'Attachment C: Curriculum Vitae',
        'description' => 'Curriculum vitae files for the project leader and participating researchers.',
        'order' => 5,
        'mode' => 'upload',
        'template_slug' => 'attachment-c-curriculum-vitae',
        'sample_slug' => 'curriculum-vitae',
        'accepted_extensions' => ['pdf', 'doc', 'docx'],
        'accepted_mime_types' => [
            'application/pdf',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'multiple' => true,
        'min_files' => 1,
        'max_files' => 10,
        'max_kilobytes' => 25600,
    ],
    'gad-checklist' => [
        'document_type' => ProposalVersionFile::TYPE_GAD_CHECKLIST,
        'label' => 'GAD Generic Checklist',
        'description' => 'The completed gender and development generic checklist.',
        'order' => 6,
        'mode' => 'upload',
        'template_slug' => 'gad-generic-checklist',
        'sample_slug' => 'gad-checklist',
        'accepted_extensions' => ['pdf', 'doc', 'docx'],
        'accepted_mime_types' => [
            'application/pdf',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => 25600,
    ],
];
