<?php

use App\Models\ProposalVersionFile;

return [
    'detailed-proposal' => [
        'document_type' => ProposalVersionFile::TYPE_DETAILED_PROPOSAL,
        'label' => 'Detailed Research Proposal',
        'workspace_button_label' => 'Open Research Proposal',
        'description' => 'The exact official form generated from structured project, narrative, team, SDG, and budget data.',
        'filename_suffix' => 'detailed-research-proposal',
        'order' => 1,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'detailed-proposal',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'work-plan' => [
        'document_type' => ProposalVersionFile::TYPE_WORK_PLAN,
        'label' => 'Attachment A: Work Plan',
        'workspace_button_label' => 'Open Work Plan',
        'description' => 'Objectives, expected outputs, activities, and an M1–M12 Attachment A sheet for each project year.',
        'filename_suffix' => 'work-plan',
        'order' => 2,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'work-plan',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'line-item-budget' => [
        'document_type' => ProposalVersionFile::TYPE_LINE_ITEM_BUDGET,
        'label' => 'Attachment B: Line-Item Budget',
        'workspace_button_label' => 'Open Line-Item Budget',
        'description' => 'Project staff, approved budget line items, automatic totals, and research-office certification.',
        'filename_suffix' => 'line-item-budget',
        'order' => 3,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'line-item-budget',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'expense-breakdown' => [
        'document_type' => ProposalVersionFile::TYPE_EXPENSE_BREAKDOWN,
        'label' => 'Estimated Expense Breakdown',
        'workspace_button_label' => 'Open Expense Breakdown',
        'description' => 'Accounts, sub-accounts, expense details, quantities, unit costs, automatic subtotals, and the final estimated total.',
        'filename_suffix' => 'estimated-expense-breakdown',
        'order' => 4,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'expense-breakdown',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'curriculum-vitae' => [
        'document_type' => ProposalVersionFile::TYPE_CURRICULUM_VITAE,
        'label' => 'Attachment C: Curriculum Vitae',
        'workspace_button_label' => 'Open Curriculum Vitae',
        'description' => 'One generated CV package containing a complete official form for every project member.',
        'filename_suffix' => 'curriculum-vitae',
        'order' => 5,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'curriculum-vitae',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'gad-checklist' => [
        'document_type' => ProposalVersionFile::TYPE_GAD_CHECKLIST,
        'label' => 'GAD Generic Checklist',
        'workspace_button_label' => 'Open GAD Checklist',
        'description' => 'The official Box 7a Generic Checklist, reproduced from the source document with the Project Title and Project Leader filled automatically.',
        'filename_suffix' => 'gad-checklist',
        'order' => 6,
        'mode' => 'generated',
        'template_slug' => null,
        'sample_slug' => 'gad-checklist',
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 1,
        'max_files' => 1,
        'max_kilobytes' => null,
    ],
    'initial-screening-form' => [
        'document_type' => ProposalVersionFile::TYPE_INITIAL_SCREENING_FORM,
        'label' => 'Initial Screening Form',
        'workspace_button_label' => 'Open Initial Screening Form',
        'description' => 'The official evaluator form with the Project Title and Project Leader filled automatically; screening fields remain blank for the Research Office.',
        'filename_suffix' => 'initial-screening-form',
        'order' => 7,
        'mode' => 'automatic',
        'template_slug' => null,
        'sample_slug' => null,
        'accepted_extensions' => [],
        'accepted_mime_types' => [],
        'multiple' => false,
        'min_files' => 0,
        'max_files' => 0,
        'max_kilobytes' => null,
    ],
];
