@props(['tables' => []])
@php($input = 'mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-white')
<section class="space-y-4" x-data="{tables: @js($tables)}">
    <h3 class="text-lg font-bold">Research tables</h3><p class="text-sm">Add tables supporting your methods or findings. Paragraph position 0 places the table at the end of the section.</p>
    <template x-for="(table, ti) in tables" :key="ti"><div class="space-y-3 rounded-xl border border-gray-200 p-4 dark:border-slate-700">
        <label class="block text-sm font-semibold">Table caption<input :name="`terminal_data[tables][${ti}][caption]`" x-model="table.caption" required maxlength="300" class="{{ $input }}"></label>
        <div class="grid gap-3 sm:grid-cols-2"><label class="text-sm">Section<select :name="`terminal_data[tables][${ti}][section]`" x-model="table.section" class="{{ $input }}"><option value="methodology">Methodology</option><option value="results_discussion">Results and Discussion</option></select></label><label class="text-sm">After paragraph (0 = end)<input type="number" min="0" max="1000" :name="`terminal_data[tables][${ti}][after_paragraph]`" x-model="table.after_paragraph" class="{{ $input }}"></label></div>
        <div class="overflow-x-auto"><table class="w-full"><thead><tr><template x-for="(heading, ci) in table.headers" :key="ci"><th class="p-1"><input :aria-label="'Column '+(ci+1)+' heading'" :name="`terminal_data[tables][${ti}][headers][${ci}]`" x-model="table.headers[ci]" required maxlength="300" class="{{ $input }}"></th></template><th></th></tr></thead><tbody><template x-for="(row, ri) in table.rows" :key="ri"><tr><template x-for="(heading, ci) in table.headers" :key="ci"><td class="p-1"><textarea :aria-label="'Row '+(ri+1)+', column '+(ci+1)" :name="`terminal_data[tables][${ti}][rows][${ri}][${ci}]`" x-model="table.rows[ri][ci]" maxlength="5000" rows="2" class="{{ $input }}"></textarea></td></template><td><button type="button" @click="table.rows.splice(ri,1); $nextTick(() => $el.dispatchEvent(new Event('input', {bubbles:true})))" :disabled="table.rows.length === 1" class="p-2 text-xs text-red-600">Remove row</button></td></tr></template></tbody></table></div>
        <div class="flex flex-wrap gap-4 text-sm font-bold text-red-600"><button type="button" @click="table.headers.push(''); table.rows.forEach(row => row.push(''))" :disabled="table.headers.length >= 8">Add column</button><button type="button" @click="table.rows.push(table.headers.map(() => ''))" :disabled="table.rows.length >= 200">Add row</button><button type="button" @click="tables.splice(ti,1); $nextTick(() => $el.dispatchEvent(new Event('input', {bubbles:true})))">Remove table</button></div>
    </div></template>
    <button type="button" @click="tables.push({caption:'',section:'results_discussion',after_paragraph:0,headers:['',''],rows:[['','']]})" :disabled="tables.length >= 30" class="text-sm font-bold text-red-600">Add table</button>
</section>
