<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.18em] text-red-600">College research office</p><h2 class="mt-1 text-2xl font-black text-gray-900 dark:text-white">Research Coordinator</h2><p class="mt-1 text-sm text-gray-500">{{ $college ?: 'College assignment required' }} · Review, consolidate, and forward college submissions.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">College-scoped access</span></div></x-slot>

    <div class="space-y-6" x-data="{ tab: 'overview' }">
        @if(!$college)<div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">Ask the Research Head to assign your college before records can appear.</div>@endif
        @if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif

        <nav class="flex gap-2 overflow-x-auto rounded-2xl border border-gray-200 bg-white p-2 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            @foreach(['overview'=>'Overview','submissions'=>'Submissions','reports'=>'Report builder','forms'=>'Forms','calls'=>'Research calls'] as $key=>$label)<button @click="tab='{{ $key }}'" :class="tab==='{{ $key }}' ? 'bg-red-600 text-white shadow-sm' : 'text-gray-500 hover:bg-gray-50 dark:hover:bg-slate-800'" class="whitespace-nowrap rounded-xl px-4 py-2 text-xs font-black">{{ $label }}</button>@endforeach
        </nav>

        <section x-show="tab==='overview'" class="space-y-6">
            <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                @foreach([['Active researchers',$activeResearchers,'text-blue-700 bg-blue-50'],['Pending submissions',$topics->whereIn('status',['pending','resubmitted'])->count(),'text-amber-700 bg-amber-50'],['In progress',$topics->whereIn('status',['approved','expert_review'])->count(),'text-violet-700 bg-violet-50'],['Reports due',$topics->where('status','approved')->count(),'text-red-700 bg-red-50']] as [$label,$value,$style])<article class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-bold uppercase tracking-wider text-gray-400">{{ $label }}</p><p class="mt-3 inline-flex rounded-xl px-3 py-1 text-2xl font-black {{ $style }}">{{ $value }}</p></article>@endforeach
            </div>
            <div class="grid gap-6 lg:grid-cols-[1fr_340px]">
                <article class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-black">College project portfolio</h3><div class="mt-4 space-y-3">@forelse($topics->take(6) as $topic)<div class="flex items-center justify-between gap-4 rounded-xl bg-gray-50 p-4 dark:bg-slate-800"><div><p class="text-sm font-bold">{{ $topic->title }}</p><p class="mt-1 text-xs text-gray-500">{{ $topic->user->name }} · {{ $topic->researchCall->title }}</p></div><span class="rounded-full bg-white px-2.5 py-1 text-[10px] font-black uppercase text-gray-600 dark:bg-slate-700 dark:text-slate-200">{{ str_replace('_',' ',$topic->status) }}</span></div>@empty<p class="py-8 text-center text-sm text-gray-400">No college projects yet.</p>@endforelse</div></article>
                <article class="rounded-2xl bg-gray-900 p-5 text-white shadow-sm"><p class="text-xs font-black uppercase tracking-wider text-red-300">Action center</p><h3 class="mt-2 text-lg font-black">Keep reports moving</h3><div class="mt-5 space-y-3 text-sm"><div class="rounded-xl bg-white/10 p-3"><b>{{ $topics->where('status','pending')->count() }}</b> submissions await initial review</div><div class="rounded-xl bg-white/10 p-3"><b>{{ $topics->where('status','approved')->count() }}</b> approved projects ready to consolidate</div></div><button @click="tab='submissions'" class="mt-5 w-full rounded-xl bg-red-600 px-4 py-3 text-xs font-black">Review submissions</button></article>
            </div>
        </section>

        <section x-show="tab==='submissions'" class="rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b p-5 dark:border-slate-800"><h3 class="font-black">Incoming submissions</h3><p class="mt-1 text-xs text-gray-500">Comment, flag concerns, or forward to the Research Head. Final approval remains with the Research Head.</p></div><div class="divide-y dark:divide-slate-800">@forelse($topics as $topic)<article class="grid gap-5 p-5 lg:grid-cols-[1fr_360px]"><div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-red-50 px-2 py-1 text-[10px] font-black uppercase text-red-700">Proposal</span><span class="rounded-full bg-gray-100 px-2 py-1 text-[10px] font-black uppercase text-gray-600">{{ str_replace('_',' ',$topic->status) }}</span></div><h4 class="mt-3 font-black">{{ $topic->title }}</h4><p class="mt-1 text-xs text-gray-500">{{ $topic->user->name }} · Submitted {{ $topic->created_at->diffForHumans() }}</p><p class="mt-3 text-sm leading-6 text-gray-600">{{ $topic->description ?: 'No summary provided.' }}</p><a href="{{ route('topics.show',$topic) }}" class="mt-3 inline-flex text-xs font-black text-red-600">Open submission →</a></div><form method="POST" action="{{ route('research_coordinator.submissions.review',$topic) }}" class="space-y-3 rounded-xl bg-gray-50 p-4 dark:bg-slate-800">@csrf<textarea name="comment" required rows="3" placeholder="Add college-level review notes…" class="w-full rounded-xl border-gray-200 bg-white text-xs dark:border-slate-700 dark:bg-slate-900"></textarea><div class="grid grid-cols-3 gap-2"><button name="action" value="comment" class="rounded-lg border border-gray-200 bg-white px-2 py-2 text-[10px] font-black text-gray-700">Comment</button><button name="action" value="flag" class="rounded-lg bg-amber-100 px-2 py-2 text-[10px] font-black text-amber-800">Flag</button><button name="action" value="forward" class="rounded-lg bg-red-600 px-2 py-2 text-[10px] font-black text-white">Forward</button></div></form></article>@empty<p class="p-10 text-center text-sm text-gray-400">No submissions from your college.</p>@endforelse</div></section>

        <section x-show="tab==='reports'" class="grid gap-6 lg:grid-cols-[1fr_340px]"><article class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-black uppercase tracking-wider text-red-600">Accomplishment report builder</p><h3 class="mt-2 text-xl font-black">{{ now()->year }} College Research Accomplishments</h3><p class="mt-2 text-sm text-gray-500">{{ $topics->where('status','approved')->count() }} approved projects available for consolidation.</p><div class="mt-6 rounded-xl border border-dashed border-gray-300 p-8 text-center"><p class="font-bold">Report workspace</p><p class="mt-1 text-xs text-gray-400">Select approved projects, review totals, then export a college-level report.</p><div class="mt-4 flex justify-center gap-2"><button class="rounded-xl bg-blue-700 px-4 py-2 text-xs font-black text-white">Export Word</button><button class="rounded-xl bg-red-600 px-4 py-2 text-xs font-black text-white">Export PDF</button></div></div></article><article class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-black">Report history</h3><p class="mt-8 text-center text-sm text-gray-400">No submitted accomplishment reports yet.</p></article></section>

        <section x-show="tab==='forms'" class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-black">Official research forms</h3><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($templates as $template)<a href="{{ route('proposal-templates.download',$template) }}" class="rounded-xl border border-gray-200 p-4 transition hover:border-red-300 hover:bg-red-50 dark:border-slate-700"><p class="text-sm font-black">{{ $template->name }}</p><p class="mt-1 text-xs text-gray-400">View or download official form</p></a>@empty<p class="text-sm text-gray-400">No active forms available.</p>@endforelse</div></section>
        <section x-show="tab==='calls'" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($calls as $call)<article class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black uppercase text-emerald-700">Active call</span><h3 class="mt-4 font-black">{{ $call->title }}</h3><p class="mt-2 text-xs leading-5 text-gray-500">{{ $call->description }}</p><p class="mt-4 text-xs font-bold text-red-600">Closes {{ $call->closes_at?->format('M d, Y') }}</p></article>@empty<p class="text-sm text-gray-400">No active research calls.</p>@endforelse</section>
    </div>
</x-app-layout>
